title : Justzero's WebSite
author :
  name : Bing Gong
  email : gb.justzero@gmail.com
  github : justzero
  twitter : justzero
  feedburner : Justzero's WebSite

navigation :
  - index.html
  - archive.html
  - about.html
  
